### PR TITLE
MAP_ANONYMOUS not valid on Yosemite, define only if needed.

### PR DESCRIPTION
**Pull request by nanjizal**

### CODE REVIEW

**Comment by nanjizal** [comment]
Andy Li is this better?

**Comment by nanjizal** [comment]
I think if missing on linux you would need alternate remap so it's better behind an if apple flag.

**Comment by andyli** [comment]
using `#ifndef` would be slightly better ;)

**Comment by nanjizal** [comment]
ah ok, amended, can't check the code on yosemite as I have now upgraded so likely no longer an issue for me but hopefully makes code more robust.

**Comment by nanjizal** [comment]
amended.

**Pull request merged**
